### ISSUE TITLE
Updates received while the app is closed do not arrive

### ISSUE THREAD

**Issue by link2xt** [webratte/Shared-Memo#29] opened 2023-07-25 04:05 UTC
See the comment https://github.com/deltachat/deltachat-core-rust/issues/4543#issuecomment-1646252326

Similar bug https://github.com/webxdc/store/issues/203 was found in the store app, but as it is a particular xdc bug, this one should be debugged separately.

**Comment by webratte** [comment] 2023-07-25 05:42
I can reproduce it.
But this happens only if I send an already filled Memo.

If I do it as follows, it works:
1.Share a new Memo
2. send it as empty (or lower then the download limit)
3. Send an update higher than the download limit.
4.Tab the download button
5.The update is imported.

If you had the same issue in the store App, maybe you can give a hint, how you fixed it?

**Comment by webratte** [comment] 2023-07-25 17:29
Strange.
With the newest nightly (https://download.delta.chat/android/nightly/2023-07-25/) as the receiver I can't reproduce it. As Sender I still use the current Gplay Version 1.38.2
Can somebody confirm this?

**Comment by webratte** [comment] 2023-08-06 14:54
Since this not happens on the newest desktop an Andriod Clients, I think I can close it as fixed bei Delta Chat.

**Closed as completed by webratte** 2023-08-06 14:54 UTC
